--movie

CREATE TABLE MOVIE 
(
  NUM NUMBER NOT NULL 
, TITLE VARCHAR2(50) NOT NULL 
, PRICE NUMBER NOT NULL 
, PRODUCER VARCHAR2(20) 
, CONSTRAINT MOVIE_PK PRIMARY KEY 
  (
    NUM 
  )
  ENABLE 
);

--RESERVATION
CREATE TABLE RESERVATION 
(
  NUM NUMBER NOT NULL 
, USER_ID VARCHAR2(20) NOT NULL 
, MOVIE_NUM NUMBER NOT NULL 
, REGDATE DATE DEFAULT sysdate 
, MOVIE_DATE DATE 
, MCOUNT NUMBER 
, CONSTRAINT RESERVATION_PK PRIMARY KEY 
  (
    NUM 
  )
  ENABLE 
);

ALTER TABLE RESERVATION
ADD CONSTRAINT RESERVATION_FK1 FOREIGN KEY
(
  USER_ID 
)
REFERENCES MEMBER
(
  ID 
)
ENABLE;

ALTER TABLE RESERVATION
ADD CONSTRAINT RESERVATION_FK2 FOREIGN KEY
(
  MOVIE_NUM 
)
REFERENCES MOVIE
(
  NUM 
)
ENABLE;


--------------------------
CREATE sequence SEQ_MOVIE ;
CREATE sequence SEQ_RESERVATION ;